import "~/styles/globals.css";

import { TRPCReactProvider } from "~/trpc/react";
import AuthProvider from "~/providers/AuthProvider";
import { UIProvider } from "~/providers/UIProvider";

export const metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="font-cairo">
        <UIProvider>
          <AuthProvider>
            <TRPCReactProvider>{children}</TRPCReactProvider>
          </AuthProvider>
        </UIProvider>
      </body>
    </html>
  );
}
